services:
  postgres:
    image: postgres:latest
    container_name: gendev_postgres_db
    environment:
      POSTGRES_DB: gendevdb
      POSTGRES_USER: gendev
      POSTGRES_PASSWORD: p@ssw0rd1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5500:5432"
    restart: unless-stopped

volumes:
  postgres_data: